### ISSUE TITLE
sysctl_runtime should print error and not raise PuppetError on non-existent sysctl key

### ISSUE THREAD

**Issue by tobias-urdin** [duritong/puppet-sysctl#44]
In lib/puppet/provider/sysctl_runtime/sysctl_runtime.rb we are throwing a PuppetError which stops the whole execution of that puppet run. We should issue a warning here instead and let puppet continue, when we exit this might cause nodes to be in an inconsistent state for no reason.

> raise(Puppet::ParseError, "sysctl parameter #{res} wasn't found on this system")

There is no harm in continuing since we probably got a invalid sysctl value or a sysctl value that only exists if some Linux module is loaded, this should be up to the user to validate.

**Comment by duritong** [comment]
It's only during prefetch, right? If we want to set the value and it's non-existent, then the resource itself still fails?

I agree that we shouldn't fail hard during prefetch, BUT we must fail when managing the resource.

**Comment by tobias-urdin** [comment]
This was actually caused by an issue on our side where we in testing installed a package that loaded the `br_netfilter` linux module but we didn't do this in production causing the sysctl key we wanted to set to not be available so sysctl `raise`d that failure and the node was left in an inconsistent state.

I think this is a valid change but it was more a small change to fix the issue before we knew what it was.
Feel free to tkae a decision if you want this to merge or not.

Yes this is only in prefetch so it will output warnings, do a complete puppet run then have a failed run instead if the sysctl_runtime resource fails to set the sysctl value for that key.

I verified with `puppet apply` with `--detailed-exitcodes` that the `sysctl_runtime` resource returns exit code `4` if the resource fails when the key doesn't exist so it's a failure error code (0 = nothing changed, 2 = changes, all others is considered failures).

**Comment by duritong** [comment]
merged, thank you!
